import type { EditorThemeClasses } from 'lexical';

export const EditorTheme: EditorThemeClasses = {
  root: 'prose prose-sm dark:prose-invert max-w-none',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'font-mono bg-gray-100 dark:bg-gray-800 rounded px-1',
  },
  paragraph: 'my-2',
  heading: {
    h1: 'text-3xl font-bold my-4',
    h2: 'text-2xl font-bold my-3',
    h3: 'text-xl font-bold my-2',
    h4: 'text-lg font-bold my-2',
    h5: 'text-base font-bold my-1',
    h6: 'text-sm font-bold my-1',
  },
  list: {
    ul: 'list-disc list-inside my-2',
    ol: 'list-decimal list-inside my-2',
    listitem: 'my-1',
    nested: {
      listitem: 'ml-4',
    },
    checklist: 'list-none',
  },
  table: 'border-collapse border border-gray-300 dark:border-gray-700 my-4',
  tableCell: 'border border-gray-300 dark:border-gray-700 p-2',
  tableRow: 'even:bg-gray-50 dark:even:bg-gray-800',
  link: 'text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500 underline',
  quote: 'border-l-4 border-gray-300 dark:border-gray-700 pl-4 my-4 italic',
  code: 'font-mono bg-gray-100 dark:bg-gray-800 rounded px-1',
  codeHighlight: {
    atrule: 'text-blue-500',
    attr: 'text-purple-500',
    boolean: 'text-red-500',
    builtin: 'text-teal-500',
    cdata: 'text-gray-500',
    char: 'text-green-500',
    class: 'text-purple-500',
    'class-name': 'text-blue-500',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-500',
    deleted: 'text-red-500',
    doctype: 'text-gray-500',
    entity: 'text-yellow-500',
    function: 'text-blue-500',
    important: 'text-purple-500',
    inserted: 'text-green-500',
    keyword: 'text-purple-500',
    namespace: 'text-yellow-500',
    number: 'text-orange-500',
    operator: 'text-purple-500',
    prolog: 'text-gray-500',
    property: 'text-blue-500',
    punctuation: 'text-gray-500',
    regex: 'text-red-500',
    selector: 'text-green-500',
    string: 'text-green-500',
    symbol: 'text-purple-500',
    tag: 'text-red-500',
    url: 'text-blue-500',
    variable: 'text-purple-500',
  },
};
